### ISSUE TITLE
Attribute used when declare property

### ISSUE THREAD

**Issue by tomisacat** [miscavage/Popup#2]
I noticed that you declare the UIColor property with attribute *assign*, I wonder why not strong but assign?

**Comment by magdics** [comment]
How can I have the popup load the previously entered data into the textfields upon launch?

**Comment by miscavage** [comment]
@tomisacat you're right, should be strong. Fixing it now and will be in next commit

**Comment by miscavage** [comment]
@magdics you wouldn't be able to do that since every Popup gets reinitiated every time you call it, gets added to the view and removed. You can mess with the initiation process a bit and perhaps remove some instances where I show/add and dismiss/remove. But what would be easier is just calling the same block of code everywhere you need it.
I'll look into it more and if anything seems like it'll work i'll commit and/or you can submit a pull request if you get it to work!
Thanks!
